server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: apply
          uri: http://localhost:8082
          predicates:
            - Path=/applies/**, 
        - id: send
          uri: http://localhost:8083
          predicates:
            - Path=/sends/**, 
        - id: limit
          uri: http://localhost:8084
          predicates:
            - Path=/limits/**, 
        - id: customer
          uri: http://localhost:8085
          predicates:
            - Path=/customers/**, 
        - id: mypage
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: apply
          uri: http://apply:8080
          predicates:
            - Path=/applies/**, 
        - id: send
          uri: http://send:8080
          predicates:
            - Path=/sends/**, 
        - id: limit
          uri: http://limit:8080
          predicates:
            - Path=/limits/**, 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/customers/**, 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
