apiVersion: apps/v1
kind: Deployment
metadata:
  name: limit
  labels:
    app: limit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limit
  template:
    metadata:
      labels:
        app: limit
    spec:
      containers:
        - name: limit
          image: "username/limit:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
